
A user '{{ user.fullname }}' has raised an issue with one of your datasets on {{ site_title }}.

The dataset is: {{ dataset.title }}
The issue is:

    {{ issue_subject }}
    "{{ issue.description }}"

Please correct the problem or add an initial comment about the issue at: {{ h.url_for('issues_show', dataset_id=dataset.name, issue_number=issue.number, qualified=True) }}. Once the issue has been resolved, click 'Close issue'.

Thank you,

The {{ site_title }} team

--

Issue: {{ h.url_for('issues_show', dataset_id=dataset.name, issue_number=issue.number, qualified=True) }}
Dataset: {{ h.url_for('dataset_read', id=dataset.name, qualified=True) }}

